module Test.Da4
  where

import qualified Data.List as L
import CLaSH.Prelude
import CLaSH.Prelude.Explicit

import Clocks
import Da4

-- let a = simulateB da4 $ L.replicate 101 (0,1)
-- putStrLn $ show $ (L.take 101 a :: [(Bit, Bit)])

-- The second high bit means we are running in debug mode
testInput :: Signal' SClk36 (BitVector 12, Bit)
testInput = stimuliGenerator' sclk2 $(v (L.replicate 108 (0::BitVector 12, 1 :: Bit)) )

runTest = sampleN 108 $ expectedOutput $ bundle' sclk2 $ da4 $ unbundle' sclk2 testInput

expectedOutput :: Signal' SClk36 (Bit, Bit) -> Signal' SClk36 Bool
expectedOutput = outputVerifier' sclk2 $(v [(0 :: Bit, 0 :: Bit)  -- packet 0
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     -- packet 1
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     -- packet
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (1, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (1, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 0)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     , (0, 1)
                                     -- packet
                                     ])
